<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<NoWarn>1591</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="EasyNetQ" Version="8.1.4" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
		<PackageReference Include="System.Windows.Extensions" Version="10.0.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Autobarn.Data\Autobarn.Data.csproj" />
		<ProjectReference Include="..\Autobarn.Messages\Autobarn.Messages.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="boing.wav">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
