<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greet.proto

namespace GPBMetadata;

class Greet
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xAB\x01\x0A\x0Bgreet.proto\x12\x05greet\"\x1C\x0A\x0CHelloRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\"\x1D\x0A\x0AHelloReply\x12\x0F\x0A\x07message\x18\x01 \x01(\x092=\x0A\x07Greeter\x122\x0A\x08SayHello\x12\x13.greet.HelloRequest\x1A\x11.greet.HelloReplyB\x11\xAA\x02\x0EGreetingServerb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

