// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: greet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package greet;

@kotlin.jvm.JvmName("-initializehelloRequest")
public inline fun helloRequest(block: greet.HelloRequestKt.Dsl.() -> kotlin.Unit): greet.Greet.HelloRequest =
  greet.HelloRequestKt.Dsl._create(greet.Greet.HelloRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * The request message containing the user's name.
 * ```
 *
 * Protobuf type `greet.HelloRequest`
 */
public object HelloRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: greet.Greet.HelloRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: greet.Greet.HelloRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): greet.Greet.HelloRequest = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun greet.Greet.HelloRequest.copy(block: `greet`.HelloRequestKt.Dsl.() -> kotlin.Unit): greet.Greet.HelloRequest =
  `greet`.HelloRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

