// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: greet.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package greet;

@kotlin.jvm.JvmName("-initializehelloReply")
public inline fun helloReply(block: greet.HelloReplyKt.Dsl.() -> kotlin.Unit): greet.Greet.HelloReply =
  greet.HelloReplyKt.Dsl._create(greet.Greet.HelloReply.newBuilder()).apply { block() }._build()
/**
 * ```
 * The response message containing the greetings.
 * ```
 *
 * Protobuf type `greet.HelloReply`
 */
public object HelloReplyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: greet.Greet.HelloReply.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: greet.Greet.HelloReply.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): greet.Greet.HelloReply = _builder.build()

    /**
     * `string message = 1;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 1;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun greet.Greet.HelloReply.copy(block: `greet`.HelloReplyKt.Dsl.() -> kotlin.Unit): greet.Greet.HelloReply =
  `greet`.HelloReplyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

